openapi: "3.0.2"
info:
paths:
components:
  schemas:
    InvalidRequest:
      title: InvalidRequest
      type: object
      required:
        - jsonrpc
        - id
        - error
      properties:
        jsonrpc:
          type: string
          default: "2.0"
        id:
          type: integer
          format: int64
        error:
          type: object
          title: ErrorMember
          required:
            - code
          properties:
            message:
              type: string
              default: Invalid Request
            data:
              type: string
            code:
              type: integer
              format: int32
              default: -32600
              description: >-
                The JSON sent is not a valid Request object.
