openapi: "3.0.2"
info:
paths:
components:
  schemas:
    MethodNotFound:
      title: MethodNotFound
      type: object
      required:
        - jsonrpc
        - id
        - error
      properties:
        jsonrpc:
          type: string
          default: "2.0"
        id:
          type: integer
          format: int64
        error:
          type: object
          title: ErrorMember
          required:
            - code
          properties:
            message:
              type: string
              default: Method not found
            data:
              type: string
            code:
              type: integer
              format: int32
              default: -32601
              description: >-
                The method does not exist / is not available.
