openapi: "3.0.2"
info:
paths:
components:
  schemas:
    ParseError:
      type: object
      required:
        - jsonrpc
        - id
        - error
      properties:
        jsonrpc:
          type: string
          default: "2.0"
        id:
          type: integer
          format: int64
        error:
          type: object
          title: ErrorMember
          required:
            - code
          properties:
            message:
              type: string
              default: Parse error
            data:
              type: string
            code:
              type: integer
              format: int32
              default: -32700
              description: >-
                invalid JSON was received by the server.
                An error occurred on the server while parsing the JSON text.
