openapi: "3.0.2"
info:
paths:
components:
  schemas:
    RpcCallError:
      type: object
      required:
        - jsonrpc
        - id
        - error
      properties:
        jsonrpc:
          type: string
          default: "2.0"
        id:
          type: integer
          format: int64
        error:
          type: object
          title: ErrorMember
          required:
            - code
          properties:
            code:
              type: integer
              format: int32
              description: |
                A Number that indicates the error type that occurred.
                This MUST be an integer.
            message:
              type: string
              description: |
                A String providing a short description of the error.
                The message SHOULD be limited to a concise single sentence.
            data:
              type: string
              description: |
                A Primitive or Structured value that contains additional information about the error.
                This may be omitted.
                The value of this member is defined by the Server (e.g. detailed error information, nested errors etc.).

                
