openapi: "3.0.2"
info:
paths:
components:
  schemas:
    ServerError:
      title: ServerError
      type: object
      required:
        - jsonrpc
        - id
        - error
      properties:
        jsonrpc:
          type: string
          default: "2.0"
        id:
          type: integer
          format: int64
        error:
          type: object
          title: ErrorMember
          required:
            - code
          properties:
            message:
              type: string
              default: Server error
            data:
              type: string
            code:
              type: integer
              format: int32
              default: -32000
              description: >-
                -32000 to -32099 </br>
                Reserved for implementation-defined server-errors.
