openapi: "3.0.2"
info:
paths:
components:
  schemas:
    RewardSpecResult:
      type: object
      properties:
        result:
          $ref: "#/components/schemas/RewardSpec"
    RewardSpec:
      title: RewardSpec
      description: |
        <SchemaDefinition schemaRef="#/components/schemas/RewardSpec" />
      type: object
      required:
        - burnFee
        - kfg
        - kir
        - minted
        - proposer
        - rewards
        - stakers
        - totalFee
      properties:
        burnFee:
          type: integer
          format: int64
          description: the amount burnt
        kgf:
          type: integer
          format: int64
          description: the amount allocated to KGF
        kir:
          type: integer
          format: int64
          description: the amount allocated to KIR
        minted:
          type: number
          format: double
          description: the amount newly minted
          example: 9600000000000000000
        proposer:
          type: number
          format: double
          description: the amount allocated to the block proposer
          example: 9600000000000000000
        rewards:
          type: object
          description: mapping from reward recipient to amounts
          additionalProperties:
            type: number
            format: double
          example:
            0xb408fc9b2512284823264aceeb50d2970533b4ff: 9600000000000000000
        stakers:
          type: integer
          format: int64
          description: total amount allocated to stakers
        totalFee:
          type: integer
          format: int64
          description: total tx fee spent
