generatorName: caver-java
outputDir: ./openapi
inputSpec: ../../../site/klaytn-openapi.yaml
groupId: klaytn.foundation
artifactId: caver-java
artifactVersion: v1.10.0
library: retrofit2
templateDir: ./template
globalProperties:
  apiDocs: false
  modelDocs: false
  apiTests: false
  modelTests: false
additionalProperties:
  # This open is related json nullable, so it should be off.
  openApiNullable: false
  apiPackage: caver.sdk.apis
  modelPackage: caver.sdk.models
