generatorName: typescript-axios
outputDir: ./api/klay/account
inputSpec: ../api/klay.account-api.yaml
templateDir: ./template
additionalProperties:
  withInterfaces: false
  apiPackage: sdk.api
  modelPackage: sdk.model
  withSeparateModelsAndApi: true
  useSingleRequestParameter: false
  stringEnums: true
