generatorName: klaytn-typescript-axios
outputDir: ./openapi/klay
inputSpec: ../api/klay-api.yaml
templateDir: ./template
additionalProperties:
  withInterfaces: false
  apiPackage: api
  modelPackage: model
  withSeparateModelsAndApi: true
  useSingleRequestParameter: false
  stringEnums: true
files:
  apiInner.mustache:
    templateType: API
    destinationFilename: .ts
  model.mustache:
    templateType: Model
    destinationFilename: .ts
