openapi: "3.0.2"
info:
  title: KLAY OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /klay/accountCreated:
    post:
      operationId: accountCreated
      summary: "[accountCreated] Find if input address was created"
      description: |
        Returns `true` if the account associated with the address is created. It returns `false` otherwise.

        **JSONRPC:** `klay_accountCreated`

        **NOTE:** *In versions earlier than Klaytn v1.7.0, only integer block number, the string "earliest" and "latest" are available.*
      tags:
        - klay.account
      parameters:
        - name: address
          required: true
          schema:
            type: string
            format: 20-byte DATA
            readOnly: true
          description: Address
          in: query
        - name: blockNumber
          required: true
          schema:
            oneOf:
              - type: number
                format: double
                title: blockNumber
                description: BN | BigNumber
              - type: string
                title: blockTag
                example: [latest, pending, earliest]
            readOnly: true
          description: |
            Integer or hexadecimal block number, or the string `earliest`, `latest` or `pending` as in the [default block parameter](https://docs.klaytn.foundation/dapp/json-rpc/api-references/klay/block#the-default-block-parameter), or block hash.
          in: query
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - type: object
                  properties:
                    method:
                      type: string
                      default: klay_accountCreated
                    params:
                      example:
                        ["0xa4f42d4d2a3a13874406435500950c9bf2d783db", "latest"]
      responses:
        default:
          description: The existence of an input address
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - type: object
                    properties:
                      result:
                        type: boolean
      externalDocs:
        url: https://docs.klaytn.foundation/dapp/json-rpc/api-references/klay/account#klay_accountcreated
        description: Klaytn Docs
      x-codeSamples:
        - lang: "typescript"
          label: "Typescript"
          source:
            $ref: "../../../sdk/client/typescript-axios/test/klay/account/accountCreated.test.ts"
        - lang: "curl"
          label: "Curl"
          source:
            $ref: "../../code-samples/klay/account/accountCreated.sh"
  /klay/accountCreated2:
    post:
      operationId: accountCreated2
      summary: "[accountCreated] Find if input address was created"
      description: |
        Returns `true` if the account associated with the address is created. It returns `false` otherwise.

        **JSONRPC:** `klay_accountCreated`

        **NOTE:** *In versions earlier than Klaytn v1.7.0, only integer block number, the string "earliest" and "latest" are available.*
      tags:
        - klay.account
      parameters:
        - name: address
          schema:
            type: string
            format: 20-byte DATA
            readOnly: true
          description: Address
          in: query
        - name: blockNumber
          required: true
          schema:
            type: number
            readOnly: true
          description: Address
          in: query
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - type: object
                  properties:
                    method:
                      type: string
                      default: klay_accountCreated
                    params:
                      example:
                        ["0xa4f42d4d2a3a13874406435500950c9bf2d783db", "latest"]
      responses:
        default:
          description: The existence of an input address
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - type: object
                    properties:
                      result:
                        type: boolean
      externalDocs:
        url: https://docs.klaytn.foundation/dapp/json-rpc/api-references/klay/account#klay_accountcreated
        description: Klaytn Docs
      x-codeSamples:
        - lang: "typescript"
          label: "Typescript"
          source:
            $ref: "../../../sdk/client/typescript-axios/test/klay/account/accountCreated.test.ts"
        - lang: "curl"
          label: "Curl"
          source:
            $ref: "../../code-samples/klay/account/accountCreated.sh"
