openapi: "3.0.2"
info:
  title: ERROR OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

components:
  responses:
    JsonRpcResponseError:
      description: When a rpc call encounters an error, the Response Object MUST contain the error member.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RpcCallError'
    ParseResponseError:
      description: When a rpc call encounters an error, the Response Object MUST contain the error member.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ParseError'
  schemas:
    RpcCallError:
      type: object
      required:
        - jsonrpc
        - id
        - error
      properties:
        jsonrpc:
          type: string
          default: "2.0"
        id:
          type: integer
          format: int64
        error:
          $ref: "#/components/schemas/ErrorMember"

    ErrorMember:
      type: object
      required:
        - code
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        data:
          type: string
    ParseError:
      allOf:
        - $ref: "#/components/schemas/RpcCallError"
        - type: object
          properties:
            error:
              type: object
              properties:
                code:
                  type: integer
                  default: -32700
                  description: >
                    invalid JSON was received by the server.
                    An error occurred on the server while parsing the JSON text.

paths:

