openapi: "3.0.2"
info:
paths:
components:
  schemas:
    JsonRpcRequest:
      type: object
      required:
        - method
        - id
        - jsonrpc
      properties:
        method:
          type: string
          description: Method name
        id:
          type: integer
          default: 1
          format: int32
          description: Request ID
        jsonrpc:
          type: string
          default: "2.0"
          description: JSON-RPC Version (2.0)
        params:
          type: array
          items: {}
